package aSintatico;


//----------------------------------------------------
//The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public interface sym {
/* terminals */
public static final int FCHAVE = 34;
public static final int NUMBER_DOUBLE = 45;
public static final int MULT = 24;
public static final int IMPRIMIR = 9;
public static final int NOT_EQUAL = 17;
public static final int ASSING = 41;
public static final int MINUS = 23;
public static final int PONTO = 39;
public static final int VIRGULA = 37;
public static final int STATIC = 7;
public static final int NOT = 40;
public static final int AND = 15;
public static final int LT = 18;
public static final int OR = 14;
public static final int GET = 21;
public static final int CLASS = 2;
public static final int DIV = 25;
public static final int PLUS = 22;
public static final int ACHAVE = 33;
public static final int MAIN = 3;
public static final int IF = 11;
public static final int ACOLCHETE = 35;
public static final int THIS = 29;
public static final int BOOLEAN = 46;
public static final int EOF = 0;
public static final int RETURN = 13;
public static final int EQUAL = 16;
public static final int PVIRGULA = 38;
public static final int TRUE = 28;
public static final int NEW = 30;
public static final int error = 1;
public static final int NUMBER = 44;
public static final int FCOLCHETE = 36;
public static final int MOD = 26;
public static final int VOID = 8;
public static final int ELSE = 12;
public static final int WHILE = 10;
public static final int LET = 19;
public static final int PUBLIC = 5;
public static final int EXTENDS = 6;
public static final int APARENTESE = 31;
public static final int FPARENTESE = 32;
public static final int STRING = 43;
public static final int FALSE = 27;
public static final int GT = 20;
public static final int LENGTH = 42;
public static final int IDENTIFIER = 4;
public static final String[] terminalNames = new String[] {
"EOF",
"error",
"CLASS",
"MAIN",
"IDENTIFIER",
"PUBLIC",
"EXTENDS",
"STATIC",
"VOID",
"IMPRIMIR",
"WHILE",
"IF",
"ELSE",
"RETURN",
"OR",
"AND",
"EQUAL",
"NOT_EQUAL",
"LT",
"LET",
"GT",
"GET",
"PLUS",
"MINUS",
"MULT",
"DIV",
"MOD",
"FALSE",
"TRUE",
"THIS",
"NEW",
"APARENTESE",
"FPARENTESE",
"ACHAVE",
"FCHAVE",
"ACOLCHETE",
"FCOLCHETE",
"VIRGULA",
"PVIRGULA",
"PONTO",
"NOT",
"ASSING",
"LENGTH",
"STRING",
"NUMBER",
"NUMBER_DOUBLE",
"BOOLEAN"
};
}


