/* The following code was generated by JFlex 1.3.5 on 13/12/15 23:35 */

import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;

 

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 13/12/15 23:35 from the specification file
 * <tt>file:/home/nymeria/workspace/git/TypeChecking/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\2\1\2\0\1\1\22\0\1\1\1\40\3\0\1\45\1\36"+
    "\1\0\1\46\1\47\1\3\1\43\1\54\1\44\1\7\1\2\1\6"+
    "\11\4\1\0\1\55\1\41\1\37\1\42\2\0\10\5\1\16\21\5"+
    "\1\52\1\0\1\53\1\0\1\5\1\0\1\21\1\25\1\17\1\30"+
    "\1\13\1\34\1\56\1\33\1\23\2\5\1\20\1\12\1\10\1\15"+
    "\1\24\1\5\1\14\1\22\1\27\1\11\1\31\1\32\1\26\2\5"+
    "\1\50\1\35\1\51\uff82\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    47,    94,    47,   141,   188,   235,    47,   282,   329, 
      376,   423,   470,   517,   564,   611,   658,   705,   752,   799, 
      846,   893,   940,   987,  1034,  1081,  1128,  1175,    47,    47, 
       47,    47,    47,    47,    47,    47,    47,    47,    47,  1222, 
     1269,   235,  1316,  1363,  1410,  1457,  1504,  1551,  1598,  1645, 
     1692,   188,  1739,  1786,  1833,  1880,  1927,  1974,  2021,    47, 
       47,    47,    47,    47,    47,  2068,  2115,   188,  2162,  2209, 
     2256,  2303,  2350,  2397,  2444,   188,  2491,  2538,  2585,  2632, 
     2679,  2726,  2773,  2820,   188,   188,  2867,  2914,  2961,  3008, 
     3055,  3102,  3149,   188,   188,   188,  3196,  3243,  3290,  3337, 
     3384,   188,  3431,  3478,  3525,  3572,   188,   188,  3619,  3666, 
      188,   188,   188,   188,  3713,  3760,   188,   188,  3807
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\0\1\2\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\6\1\12\1\13\1\14\2\6\1\15\1\16"+
    "\1\6\1\17\1\20\1\21\1\22\1\6\1\23\1\6"+
    "\1\24\1\25\1\6\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\6\62\0\1\50"+
    "\57\0\1\5\1\0\1\5\1\51\53\0\3\6\1\0"+
    "\25\6\21\0\1\6\4\0\1\52\1\0\1\52\1\51"+
    "\53\0\3\6\1\0\3\6\1\53\21\6\21\0\1\6"+
    "\4\0\3\6\1\0\11\6\1\54\13\6\21\0\1\6"+
    "\4\0\3\6\1\0\10\6\1\55\5\6\1\56\6\6"+
    "\21\0\1\6\4\0\3\6\1\0\3\6\1\57\21\6"+
    "\21\0\1\6\4\0\3\6\1\0\10\6\1\60\14\6"+
    "\21\0\1\6\4\0\3\6\1\0\3\6\1\61\21\6"+
    "\21\0\1\6\4\0\3\6\1\0\17\6\1\62\5\6"+
    "\21\0\1\6\4\0\3\6\1\0\1\63\23\6\1\64"+
    "\21\0\1\6\4\0\3\6\1\0\1\6\1\65\23\6"+
    "\21\0\1\6\4\0\3\6\1\0\5\6\1\66\17\6"+
    "\21\0\1\6\4\0\3\6\1\0\4\6\1\67\16\6"+
    "\1\70\1\6\21\0\1\6\4\0\3\6\1\0\5\6"+
    "\1\71\17\6\21\0\1\6\4\0\3\6\1\0\23\6"+
    "\1\72\1\6\21\0\1\6\4\0\3\6\1\0\11\6"+
    "\1\73\13\6\21\0\1\6\35\0\1\74\57\0\1\75"+
    "\57\0\1\76\56\0\1\77\56\0\1\100\56\0\1\101"+
    "\17\0\3\50\1\102\53\50\10\0\1\103\52\0\3\6"+
    "\1\0\22\6\1\104\2\6\21\0\1\6\4\0\3\6"+
    "\1\0\13\6\1\105\11\6\21\0\1\6\4\0\3\6"+
    "\1\0\12\6\1\106\12\6\21\0\1\6\4\0\3\6"+
    "\1\0\17\6\1\107\5\6\21\0\1\6\4\0\3\6"+
    "\1\0\17\6\1\110\5\6\21\0\1\6\4\0\3\6"+
    "\1\0\11\6\1\111\13\6\21\0\1\6\4\0\3\6"+
    "\1\0\1\112\24\6\21\0\1\6\4\0\3\6\1\0"+
    "\11\6\1\113\13\6\21\0\1\6\4\0\3\6\1\0"+
    "\17\6\1\114\5\6\21\0\1\6\4\0\3\6\1\0"+
    "\15\6\1\115\7\6\21\0\1\6\4\0\3\6\1\0"+
    "\5\6\1\116\17\6\21\0\1\6\4\0\3\6\1\0"+
    "\1\6\1\117\23\6\21\0\1\6\4\0\3\6\1\0"+
    "\13\6\1\120\11\6\21\0\1\6\4\0\3\6\1\0"+
    "\13\6\1\121\11\6\21\0\1\6\4\0\3\6\1\0"+
    "\13\6\1\122\11\6\21\0\1\6\4\0\3\6\1\0"+
    "\10\6\1\123\14\6\21\0\1\6\2\50\1\2\1\102"+
    "\53\50\11\0\1\124\51\0\3\6\1\0\1\125\24\6"+
    "\21\0\1\6\4\0\3\6\1\0\3\6\1\126\21\6"+
    "\21\0\1\6\4\0\3\6\1\0\3\6\1\127\21\6"+
    "\21\0\1\6\4\0\3\6\1\0\1\6\1\130\23\6"+
    "\21\0\1\6\4\0\3\6\1\0\12\6\1\131\12\6"+
    "\21\0\1\6\4\0\3\6\1\0\25\6\21\0\1\132"+
    "\4\0\3\6\1\0\17\6\1\133\5\6\21\0\1\6"+
    "\4\0\3\6\1\0\10\6\1\134\14\6\21\0\1\6"+
    "\4\0\3\6\1\0\10\6\1\135\14\6\21\0\1\6"+
    "\4\0\3\6\1\0\3\6\1\136\21\6\21\0\1\6"+
    "\4\0\3\6\1\0\12\6\1\137\12\6\21\0\1\6"+
    "\4\0\3\6\1\0\20\6\1\140\4\6\21\0\1\6"+
    "\4\0\3\6\1\0\10\6\1\141\14\6\21\0\1\6"+
    "\4\0\3\6\1\0\12\6\1\142\12\6\21\0\1\6"+
    "\12\0\1\143\50\0\3\6\1\0\1\144\24\6\21\0"+
    "\1\6\4\0\3\6\1\0\4\6\1\145\20\6\21\0"+
    "\1\6\4\0\3\6\1\0\12\6\1\146\12\6\21\0"+
    "\1\6\4\0\3\6\1\0\17\6\1\147\5\6\21\0"+
    "\1\6\4\0\3\6\1\0\13\6\1\150\11\6\21\0"+
    "\1\6\4\0\3\6\1\0\13\6\1\151\11\6\21\0"+
    "\1\6\4\0\3\6\1\0\3\6\1\152\21\6\21\0"+
    "\1\6\4\0\3\6\1\0\3\6\1\153\21\6\21\0"+
    "\1\6\4\0\3\6\1\0\3\6\1\154\21\6\21\0"+
    "\1\6\13\0\1\155\47\0\3\6\1\0\20\6\1\156"+
    "\4\6\21\0\1\6\4\0\3\6\1\0\1\157\24\6"+
    "\21\0\1\6\4\0\3\6\1\0\23\6\1\160\1\6"+
    "\21\0\1\6\4\0\3\6\1\0\7\6\1\161\15\6"+
    "\21\0\1\6\4\0\3\6\1\0\7\6\1\162\15\6"+
    "\21\0\1\6\4\0\3\6\1\0\11\6\1\163\13\6"+
    "\21\0\1\6\14\0\1\164\46\0\3\6\1\0\12\6"+
    "\1\165\12\6\21\0\1\6\4\0\3\6\1\0\1\166"+
    "\24\6\21\0\1\6\15\0\1\167\57\0\1\167\40\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  9,  1,  9,  1,  1,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  0,  0,  1,  1,  1,  1,  9,  9,  9,  9, 
     9,  9,  9,  9,  9,  9,  9,  0,  0,  0,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  9,  9,  9,  9, 
     9,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1, 
     1,  1,  1,  0,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
    public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
        this(is);
        symbolFactory = sf;
    }
    public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
        this(reader);
        symbolFactory = sf;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
        return symbolFactory.newSymbol(name, code,
                        new Location(yyline+1,yycolumn+1, yychar), // -yylength()
                        new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
                );
    }
    public Symbol symbol(String name, int code, String lexem){
    return symbolFactory.newSymbol(name, code, 
                        new Location(yyline+1, yycolumn +1, yychar), 
                        new Location(yyline+1,yycolumn+yylength(), yychar+yylength()), lexem);
    }
    
    protected void emit_warning(String message){
        System.out.println("scanner warning: " + message + " at : 2 "+ 
                (yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
        System.out.println("scanner error: " + message + " at : 2" + 
                (yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[3854];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 128) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 5: 
        case 8: 
        case 9: 
        case 10: 
        case 11: 
        case 12: 
        case 13: 
        case 14: 
        case 15: 
        case 16: 
        case 17: 
        case 18: 
        case 19: 
        case 20: 
        case 21: 
        case 42: 
        case 43: 
        case 44: 
        case 45: 
        case 46: 
        case 47: 
        case 48: 
        case 49: 
        case 50: 
        case 52: 
        case 53: 
        case 54: 
        case 55: 
        case 56: 
        case 57: 
        case 58: 
        case 68: 
        case 69: 
        case 70: 
        case 71: 
        case 72: 
        case 73: 
        case 74: 
        case 76: 
        case 77: 
        case 78: 
        case 79: 
        case 80: 
        case 81: 
        case 82: 
        case 86: 
        case 87: 
        case 88: 
        case 89: 
        case 90: 
        case 91: 
        case 92: 
        case 96: 
        case 97: 
        case 99: 
        case 100: 
        case 102: 
        case 103: 
        case 104: 
        case 105: 
        case 109: 
        case 114: 
          { return symbolFactory.newSymbol("IDENTIFIER", IDENTIFIER, yytext(); }
        case 120: break;
        case 27: 
          { return symbolFactory.newSymbol("GT", GT); }
        case 121: break;
        case 26: 
          { return symbolFactory.newSymbol("LT", LT); }
        case 122: break;
        case 51: 
          { return symbolFactory.newSymbol("IF", IF); }
        case 123: break;
        case 59: 
          { return symbolFactory.newSymbol("OR", OR); }
        case 124: break;
        case 4: 
        case 6: 
          { return symbolFactory.newSymbol("NUMBER", NUMBER, Integer.parseInt(yytext())); }
        case 125: break;
        case 116: 
          { return symbolFactory.newSymbol("EXTENDS", EXTENDS); }
        case 126: break;
        case 37: 
          { return symbolFactory.newSymbol("VIRGULA", VIRGULA); }
        case 127: break;
        case 107: 
          { return symbolFactory.newSymbol("FALSE", FALSE); }
        case 128: break;
        case 106: 
          { return symbolFactory.newSymbol("WHILE", WHILE); }
        case 129: break;
        case 101: 
          { return symbolFactory.newSymbol("CLASS", CLASS); }
        case 130: break;
        case 29: 
          { return symbolFactory.newSymbol("MINUS", MINUS); }
        case 131: break;
        case 7: 
          { return symbolFactory.newSymbol("PONTO", PONTO); }
        case 132: break;
        case 61: 
          { return symbolFactory.newSymbol("EQUAL", EQUAL); }
        case 133: break;
        case 32: 
          { return symbolFactory.newSymbol("FPARENTESE", FPARENTESE); }
        case 134: break;
        case 31: 
          { return symbolFactory.newSymbol("APARENTESE", APARENTESE); }
        case 135: break;
        case 30: 
          { return symbolFactory.newSymbol("MOD", MOD); }
        case 136: break;
        case 2: 
          { return symbolFactory.newSymbol("DIV", DIV); }
        case 137: break;
        case 25: 
          { return symbolFactory.newSymbol("NOT", NOT); }
        case 138: break;
        case 60: 
          { return symbolFactory.newSymbol("AND", AND); }
        case 139: break;
        case 63: 
          { return symbolFactory.newSymbol("LET", LET); }
        case 140: break;
        case 64: 
          { return symbolFactory.newSymbol("GET", GET); }
        case 141: break;
        case 67: 
          { return symbolFactory.newSymbol("NEW", NEW); }
        case 142: break;
        case 75: 
          { return symbolFactory.newSymbol("INT", INT); }
        case 143: break;
        case 117: 
          { return symbolFactory.newSymbol("BOOLEAN", BOOLEAN);; }
        case 144: break;
        case 38: 
          { return symbolFactory.newSymbol("PVIRGULA", PVIRGULA); }
        case 145: break;
        case 28: 
          { return symbolFactory.newSymbol("PLUS", PLUS); }
        case 146: break;
        case 3: 
          { return symbolFactory.newSymbol("MULT", MULT); }
        case 147: break;
        case 84: 
          { return symbolFactory.newSymbol("MAIN", MAIN); }
        case 148: break;
        case 85: 
          { return symbolFactory.newSymbol("ELSE", ELSE); }
        case 149: break;
        case 93: 
          { return symbolFactory.newSymbol("TRUE", TRUE); }
        case 150: break;
        case 94: 
          { return symbolFactory.newSymbol("THIS", THIS); }
        case 151: break;
        case 95: 
          { return symbolFactory.newSymbol("VOID", VOID); }
        case 152: break;
        case 35: 
          { return symbolFactory.newSymbol("ACOLCHETE", ACOLCHETE); }
        case 153: break;
        case 36: 
          { return symbolFactory.newSymbol("FCOLCHETE", FCOLCHETE); }
        case 154: break;
        case 62: 
          { return symbolFactory.newSymbol("NOT_EQUAL", NOT_EQUAL); }
        case 155: break;
        case 113: 
          { return symbolFactory.newSymbol("PUBLIC", PUBLIC); }
        case 156: break;
        case 112: 
          { return symbolFactory.newSymbol("STATIC", STATIC); }
        case 157: break;
        case 111: 
          { return symbolFactory.newSymbol("LENGTH", LENGTH); }
        case 158: break;
        case 110: 
          { return symbolFactory.newSymbol("RETURN", RETURN); }
        case 159: break;
        case 34: 
          { return symbolFactory.newSymbol("FCHAVE", FCHAVE); }
        case 160: break;
        case 33: 
          { return symbolFactory.newSymbol("ACHAVE", ACHAVE); }
        case 161: break;
        case 24: 
          { return symbolFactory.newSymbol("ASSING", ASSING); }
        case 162: break;
        case 118: 
          { return symbolFactory.newSymbol("NUMBER_DOUBLE", NUMBER, Double.parseDouble(yytext())); }
        case 163: break;
        case 1: 
          {  }
        case 164: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
